import swaggerUi from "swagger-ui-express";
import swaggerJsdoc from "swagger-jsdoc";
const options = {
    definition: {
      openapi: "3.0.0",
      info: {
        title: "Watch Management System",
        version: "1.0.0",
        description: "Watch Management System API with autogenerated swagger documentation",
      },
      servers: [
        { url: 'http://localhost:8082/' },
      ],
    },
    apis: ['./apiServer.js'],
  };
  
  const specs = swaggerJsdoc(options);
  export default function(app) {
    app.use("/", swaggerUi.serve, swaggerUi.setup(specs));
}

  